### ISSUE TITLE
[BUG]对toml格式解析不好

### ISSUE THREAD

**Issue by arloor** [Bin-Huang/chatbox#1487]
![image](https://github.com/user-attachments/assets/af23d315-954b-49ba-9c4e-b3aa819b4d7b)

实际是：

```toml
[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
```
